// Regenerate final-size deterministic span tables from the canonical SVG marks.
// Requires the repository web development dependencies (`npm install` in web/).
import {createRequire} from "node:module";
import {readFileSync, writeFileSync} from "node:fs";
import {resolve} from "node:path";

const require = createRequire(import.meta.url);
const {chromium} = require("../../../web/node_modules/playwright");
const SIZE = 204;
const SUNNY_SMALL_SIZE = 112;
const SUNNY_SHRINK_SIZES = [72, 44, 24];
const root = resolve(import.meta.dirname, "../../..");

function defsFrom(name) {
  const svg = readFileSync(resolve(root, "assets/brand", name), "utf8");
  const match = svg.match(/<defs>([\s\S]*?)<\/defs>/);
  if (!match) throw new Error(`${name}: missing defs`);
  return match[1];
}

async function spans(page, defs, markup, size = SIZE) {
  return page.evaluate(async ({defs, markup, size}) => {
    const source = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><defs>${defs}</defs><g fill="#fff">${markup}</g></svg>`;
    const image = new Image();
    image.src = `data:image/svg+xml;base64,${btoa(source)}`;
    await image.decode();
    const canvas = document.createElement("canvas");
    canvas.width = size;
    canvas.height = size;
    const context = canvas.getContext("2d");
    context.imageSmoothingEnabled = true;
    context.drawImage(image, 0, 0, size, size);
    const pixels = context.getImageData(0, 0, size, size).data;
    const result = [];
    for (let y = 0; y < size; y++) {
      let x = 0;
      while (x < size) {
        while (x < size && pixels[(y * size + x) * 4 + 3] < 96) x++;
        if (x == size) break;
        const x0 = x;
        while (x < size && pixels[(y * size + x) * 4 + 3] >= 96) x++;
        result.push(y, x0, x - 1);
      }
    }
    return result;
  }, {defs, markup, size});
}

function emit(name, values) {
  const lines = [];
  for (let i = 0; i < values.length; i += 24) lines.push(`  ${values.slice(i, i + 24).join(", ")},`);
  return `export const ${name}: StaticArray<i32> = [\n${lines.join("\n")}\n];\n`;
}

const browser = await chromium.launch();
try {
  const page = await browser.newPage();
  const calyxDefs = defsFrom("calyx-mark.svg");
  const sunnyDefs = defsFrom("sunny-mark.svg");
  const sunnyMarkup = [
    [0, 90, 180, 270].map((angle) => `<use href="#petal" transform="rotate(${angle} 256 256)"/>`).join(""),
    [0, 90, 180, 270].map((angle) => `<use href="#long-ray" transform="rotate(${angle} 256 256)"/>`).join(""),
    [30, 60, 120, 150, 210, 240, 300, 330].map((angle) => `<use href="#short-ray" transform="rotate(${angle} 256 256)"/>`).join(""),
  ].join("");
  const output = [
    "// Generated by build_logos.mjs from assets/brand/*.svg. Do not hand-edit.\n",
    `export const LOGO_SIZE: i32 = ${SIZE};\n`,
    emit("CALYX_PANEL_SPANS", await spans(page, calyxDefs, '<use href="#panel"/>')),
    emit("SUNNY_PETAL_SPANS", await spans(page, sunnyDefs, '<use href="#petal"/>')),
    emit("SUNNY_CARDINAL_RAYS_SPANS", await spans(page, sunnyDefs, [0, 90, 180, 270].map((angle) => `<use href="#long-ray" transform="rotate(${angle} 256 256)"/>`).join(""))),
    emit("SUNNY_DIAGONAL_A_SPANS", await spans(page, sunnyDefs, [30, 150, 210, 330].map((angle) => `<use href="#short-ray" transform="rotate(${angle} 256 256)"/>`).join(""))),
    emit("SUNNY_DIAGONAL_B_SPANS", await spans(page, sunnyDefs, [60, 120, 240, 300].map((angle) => `<use href="#short-ray" transform="rotate(${angle} 256 256)"/>`).join(""))),
    `export const SUNNY_SMALL_SIZE: i32 = ${SUNNY_SMALL_SIZE};\n`,
    emit("SUNNY_SMALL_PETAL_SPANS", await spans(page, sunnyDefs, '<use href="#petal"/>', SUNNY_SMALL_SIZE)),
    emit("SUNNY_SMALL_CARDINAL_RAYS_SPANS", await spans(page, sunnyDefs, [0, 90, 180, 270].map((angle) => `<use href="#long-ray" transform="rotate(${angle} 256 256)"/>`).join(""), SUNNY_SMALL_SIZE)),
    emit("SUNNY_SMALL_DIAGONAL_A_SPANS", await spans(page, sunnyDefs, [30, 150, 210, 330].map((angle) => `<use href="#short-ray" transform="rotate(${angle} 256 256)"/>`).join(""), SUNNY_SMALL_SIZE)),
    emit("SUNNY_SMALL_DIAGONAL_B_SPANS", await spans(page, sunnyDefs, [60, 120, 240, 300].map((angle) => `<use href="#short-ray" transform="rotate(${angle} 256 256)"/>`).join(""), SUNNY_SMALL_SIZE)),
    ...(await Promise.all(SUNNY_SHRINK_SIZES.map(async (size) =>
      `export const SUNNY_SHRINK_${size}_SIZE: i32 = ${size};\n` +
      emit(`SUNNY_SHRINK_${size}_SPANS`, await spans(page, sunnyDefs, sunnyMarkup, size))
    ))),
  ];
  writeFileSync(resolve(import.meta.dirname, "logo_assets.ts"), output.join("\n"));
} finally {
  await browser.close();
}
