#!/usr/bin/env python3
"""Tests for the named Calyx development-validation workflows."""

from __future__ import annotations

import importlib.util
import io
import subprocess
import tempfile
import unittest
from contextlib import redirect_stderr, redirect_stdout
from pathlib import Path
from unittest import mock


SPEC = importlib.util.spec_from_file_location(
    "dev", Path(__file__).with_name("dev.py")
)
assert SPEC and SPEC.loader
dev = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(dev)


class WorkflowPlanTests(unittest.TestCase):
    def test_python_test_caches_do_not_dirty_a_clean_release_checkout(self) -> None:
        with tempfile.TemporaryDirectory() as raw:
            root = Path(raw)
            (root / ".gitignore").write_bytes((dev.ROOT / ".gitignore").read_bytes())
            cache = root / "tools" / "__pycache__" / "test_dev.cpython.pyc"
            cache.parent.mkdir(parents=True)
            cache.write_bytes(b"generated bytecode")
            subprocess.run(
                ["git", "init", "--quiet", "--initial-branch=main"],
                cwd=root,
                check=True,
            )

            status = subprocess.run(
                ["git", "status", "--short", "--untracked-files=all"],
                cwd=root,
                check=True,
                capture_output=True,
                text=True,
            )

            self.assertEqual(status.stdout, "?? .gitignore\n")

    def cart(self, root: Path, relative: str) -> Path:
        cart = root / "carts" / relative
        cart.mkdir(parents=True)
        (cart / "cart.toml").write_text('[cart]\nname = "Test"\n')
        (cart / "package.json").write_text("{}\n")
        return cart

    def test_cart_resolution_supports_groups_and_rejects_local(self) -> None:
        with tempfile.TemporaryDirectory() as raw:
            root = Path(raw)
            product = self.cart(root, "demo")
            system = self.cart(root, "system/launcher")
            example = self.cart(root, "examples/hello-sunny")
            self.cart(root, ".local/external")
            self.assertEqual(dev.resolve_cart("demo", root), product)
            self.assertEqual(dev.resolve_cart("launcher", root), system)
            self.assertEqual(dev.resolve_cart("system/launcher", root), system)
            self.assertEqual(dev.resolve_cart("hello-sunny", root), example)
            self.assertEqual(dev.resolve_cart("examples/hello-sunny", root), example)
            with self.assertRaisesRegex(ValueError, "outside the first-party"):
                dev.resolve_cart(".local/external", root)
            with self.assertRaisesRegex(ValueError, "unknown runnable"):
                dev.resolve_cart("missing", root)

    def test_cart_resolution_searches_environment_overlay_roots(self) -> None:
        with tempfile.TemporaryDirectory() as raw:
            root = Path(raw)
            (root / "carts").mkdir()
            extra = root / "extra"
            private = extra / "private"
            private.mkdir(parents=True)
            (private / "cart.toml").write_text('[cart]\nname = "Private"\n')
            (private / "package.json").write_text("{}\n")

            try:
                resolved = dev.resolve_cart(
                    "private",
                    root,
                    environ={"CALYX_EXTRA_CART_ROOTS": str(extra)},
                )
            except TypeError as error:
                self.fail(f"resolve_cart does not accept an environment: {error}")

            self.assertEqual(resolved, private.resolve())

    def test_cart_resolution_ambiguity_reports_each_owning_root(self) -> None:
        with tempfile.TemporaryDirectory() as raw:
            root = Path(raw)
            public = self.cart(root, "same")
            extra = root / "extra"
            private = extra / "same"
            private.mkdir(parents=True)
            (private / "cart.toml").write_text('[cart]\nname = "Private"\n')
            (private / "package.json").write_text("{}\n")

            try:
                dev.resolve_cart(
                    "same",
                    root,
                    environ={"CALYX_EXTRA_CART_ROOTS": str(extra)},
                )
            except TypeError as error:
                self.fail(f"resolve_cart does not accept an environment: {error}")
            except ValueError as error:
                message = str(error)
                self.assertIn(str((root / "carts").resolve()), message)
                self.assertIn(str(extra.resolve()), message)
                self.assertIn("owning root", message)
            else:
                self.fail(f"duplicate cart resolved to {public}")

    def test_cart_is_build_only_not_targeted_conformance(self) -> None:
        with tempfile.TemporaryDirectory() as raw:
            root = Path(raw)
            cart = self.cart(root, "demo")
            steps = dev.cart_steps("demo", root)
            self.assertEqual(steps[-1].cwd, cart)
            self.assertEqual(steps[-1].argv, (dev.NPM, "run", "build"))
            self.assertNotIn("verify", " ".join(arg for s in steps for arg in s.argv))

    def test_canonical_sideb_refuses_to_drop_private_cart_overlay(self) -> None:
        with tempfile.TemporaryDirectory() as raw:
            root = Path(raw)
            (root / "carts").mkdir()
            private = root / "private" / "carts"
            private.mkdir(parents=True)

            with self.assertRaisesRegex(
                ValueError,
                r"python3 private/dev\.py sideb",
            ):
                dev.sideb_steps(root, environ={})

            steps = dev.sideb_steps(
                root,
                environ={"CALYX_EXTRA_CART_ROOTS": str(private)},
            )
            self.assertEqual(steps[2].label, "assemble Side B web product")

    def test_native_host_maps_supported_release_builders(self) -> None:
        cases = [
            (
                "Linux",
                "x86_64",
                "x86_64-unknown-linux-gnu",
                "linux-x86_64",
                ".tar.gz",
            ),
            (
                "Windows",
                "AMD64",
                "x86_64-pc-windows-msvc",
                "windows-x86_64",
                ".zip",
            ),
            (
                "Darwin",
                "arm64",
                "aarch64-apple-darwin",
                "macos-arm64",
                ".zip",
            ),
        ]
        for system, machine, target, label, suffix in cases:
            with self.subTest(system=system, machine=machine):
                self.assertEqual(
                    dev.native_host(system, machine),
                    dev.NativeHost(target, label, suffix),
                )

    def test_native_host_rejects_unsupported_release_builder(self) -> None:
        with self.assertRaisesRegex(ValueError, "unsupported native release host"):
            dev.native_host("Linux", "aarch64")

    def test_existing_release_archive_resolution_keeps_linux_aarch64(self) -> None:
        with tempfile.TemporaryDirectory() as raw:
            root = Path(raw)
            with (
                mock.patch.object(dev.sys, "platform", "linux"),
                mock.patch.object(dev.os, "name", "posix"),
                mock.patch.object(dev.platform, "machine", return_value="aarch64"),
            ):
                archive = dev.host_release_archive(root)
            self.assertEqual(
                archive,
                root
                / "build"
                / "distributions"
                / "calyx-1.0.0-rc.1-linux-aarch64.tar.gz",
            )

    def test_native_rehearsal_builds_then_executes_exact_host_archive(self) -> None:
        with tempfile.TemporaryDirectory() as raw:
            root = Path(raw)
            host = dev.NativeHost(
                "x86_64-pc-windows-msvc", "windows-x86_64", ".zip"
            )
            steps = dev.native_rehearsal_steps(root, host)
            self.assertEqual(
                [item.label for item in steps],
                [
                    "cart metadata",
                    "assemble release native product",
                    "verify release native product",
                ],
            )
            self.assertEqual(
                steps[1].argv[-4:],
                ("--profile", "release", "--target", "x86_64-pc-windows-msvc"),
            )
            self.assertEqual(
                steps[2].argv[-1],
                "build/distributions/calyx-1.0.0-rc.1-windows-x86_64.zip",
            )
            all_args = " ".join(arg for item in steps for arg in item.argv)
            self.assertNotIn("deploy", all_args)
            self.assertNotIn("git", all_args)

    def test_sideb_and_release_validate_but_never_deploy(self) -> None:
        sideb = dev.sideb_steps(
            environ={
                "CALYX_EXTRA_CART_ROOTS": str(dev.ROOT / "private" / "carts")
            }
        )
        self.assertEqual(
            [(item.label, item.cwd.relative_to(dev.ROOT)) for item in sideb],
            [
                ("cart metadata", Path(".")),
                ("starter build and local profile", Path(".")),
                ("assemble Side B web product", Path(".")),
                ("Side B product smoke", Path("web")),
                ("Side B touch journeys", Path("web")),
            ],
        )
        self.assertEqual(sideb[2].argv[-2:], ("--profile", "sideb"))
        release = dev.release_steps()
        all_args = " ".join(arg for item in sideb + release for arg in item.argv)
        self.assertNotIn("web_deploy", all_args)
        self.assertNotIn(" deploy ", f" {all_args} ")
        self.assertNotIn("git", all_args)
        self.assertNotIn("bless", all_args)
        self.assertTrue(any("dist-native" in item.argv for item in release))
        native_build = next(
            index for index, item in enumerate(release) if "dist-native" in item.argv
        )
        native_verify = next(
            index
            for index, item in enumerate(release)
            if "verify-native-package" in item.argv
        )
        self.assertGreater(native_verify, native_build)

    def test_commit_plan_covers_native_and_web_without_release_packaging(self) -> None:
        steps = dev.commit_steps()
        labels = [item.label for item in steps]
        self.assertEqual(
            labels,
            [
                "cart metadata",
                "Rust format",
                "Sunny font drift",
                "starter build and local profile",
                "Python tooling tests",
                "conformance harness tests",
                "Rust workspace tests",
                "native conformance",
                "web runtime tests",
                "web parity",
            ],
        )
        self.assertEqual(
            [item.cwd.relative_to(dev.ROOT) for item in steps],
            [Path(".")] * 8 + [Path("web"), Path("web")],
        )
        self.assertNotIn("release soak", labels)
        self.assertFalse(any("dist-web" in item.argv for item in steps))
        python_tests = next(
            item for item in steps if item.label == "Python tooling tests"
        )
        self.assertEqual(
            python_tests.argv,
            (
                dev.PYTHON,
                "-m",
                "unittest",
                "discover",
                "-s",
                "tools",
                "-p",
                "test_*.py",
            ),
        )


class WorkflowRunnerTests(unittest.TestCase):
    def test_dry_run_is_accepted_after_the_workflow_name(self) -> None:
        try:
            args = dev.parser().parse_args(["sideb", "--dry-run"])
        except SystemExit as error:
            self.fail(f"trailing --dry-run was rejected: {error}")
        self.assertTrue(args.dry_run)

    def test_dry_run_executes_nothing(self) -> None:
        steps = [dev.step("one", "tool", "arg")]
        with mock.patch.object(dev.subprocess, "run") as run:
            with redirect_stdout(io.StringIO()):
                self.assertEqual(dev.run_steps(steps, dry_run=True), 0)
        run.assert_not_called()

    def test_failure_stops_before_later_steps(self) -> None:
        steps = [dev.step("one", "first"), dev.step("two", "second")]
        completed = mock.Mock(returncode=7)
        with mock.patch.object(dev.subprocess, "run", return_value=completed) as run:
            with redirect_stdout(io.StringIO()), redirect_stderr(io.StringIO()):
                self.assertEqual(dev.run_steps(steps), 7)
        self.assertEqual(run.call_count, 1)
        self.assertEqual(run.call_args.args[0], ("first",))


if __name__ == "__main__":
    unittest.main()
