[cart]
name = "Calyx HD Boot"
author = "Cheesy Crab"
license = "GPL-3.0-or-later"
version = "0.2.0"
entry = "cart.ts"
abi = "v1"
role = "hd-boot"
system = true
release = false
public_source = true
display = "hd"
input = "classic"
